services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./apps/backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - ML_SERVICE_URL=http://ml:8000
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_ID=${GROQ_MODEL_ID}
    depends_on:
      - redis
    working_dir: /app/apps/backend
    volumes:
      - .:/app

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    working_dir: /app/apps/frontend
    volumes:
      - .:/app

  ml:
    build:
      context: ./apps/ml
    ports:
      - "8000:8000"
    volumes:
      - ./apps/ml:/app

  mlflow:
    build:
      context: ./apps/ml
    ports:
      - "5001:5001"
    volumes:
      - ./apps/ml:/app
    command: >
      mlflow ui
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlartifacts
      --host 0.0.0.0
      --port 5001

volumes:
  redis_data:
