"""Learn per-corridor propagation (cascade) weights from Astram incident history.

Replaces the hardcoded cascadeProbability=0.75 on every graph edge with a
corridor-specific susceptibility derived entirely from the dataset:

  * duration signal  — longer mean clearance time => longer blockage => stronger
    downstream spillover.
  * overlap signal   — how often incidents on the same corridor temporally
    overlap (compounding congestion), a direct proxy for cascade behaviour.

Both signals are min-max normalised across corridors and blended, then mapped
to a probability in [0.45, 0.90]. Corridors with too few incidents are omitted
and fall back to the backend default at serve time.

Emits a typed TS module the backend imports (no tsconfig changes needed):
    apps/backend/src/data/corridorCascade.ts

Run from apps/ml:  python -m scripts.compute_edge_weights
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

from src.data import load_and_prepare, load_config
from src.constants import DURATION_COL, BASE_DIR

MIN_INCIDENTS = 15          # corridors below this fall back to default
PROB_FLOOR, PROB_CEIL = 0.45, 0.90
DUR_WEIGHT, OVERLAP_WEIGHT = 0.6, 0.4

OUT_TS = BASE_DIR.parent / "backend" / "src" / "data" / "corridorCascade.ts"


def _overlap_rate(group: pd.DataFrame) -> float:
    """Fraction of incidents on a corridor that overlap a prior still-active one."""
    g = group.sort_values("_start_dt")
    starts = g["_start_dt"].values
    ends = (g["_start_dt"] + pd.to_timedelta(g[DURATION_COL], unit="m")).values
    overlaps = 0
    running_max_end = None
    for s, e in zip(starts, ends):
        if running_max_end is not None and s < running_max_end:
            overlaps += 1
        running_max_end = e if running_max_end is None else max(running_max_end, e)
    return overlaps / len(g) if len(g) else 0.0


def _norm(s: pd.Series) -> pd.Series:
    lo, hi = s.min(), s.max()
    if hi - lo < 1e-9:
        return pd.Series(0.5, index=s.index)
    return (s - lo) / (hi - lo)


def main():
    cfg = load_config()
    df = load_and_prepare(cfg)

    # Exclude the "Non-corridor" bucket — graph edges are only on named corridors.
    df = df[df["corridor"].notna() & (df["corridor"] != "Non-corridor")]

    stats = []
    for corridor, g in df.groupby("corridor"):
        if len(g) < MIN_INCIDENTS:
            continue
        stats.append({
            "corridor": corridor,
            "n": len(g),
            "mean_dur": float(g[DURATION_COL].mean()),
            "overlap": _overlap_rate(g),
        })

    sdf = pd.DataFrame(stats)
    sdf["dur_norm"] = _norm(sdf["mean_dur"])
    sdf["overlap_norm"] = _norm(sdf["overlap"])
    sdf["susceptibility"] = DUR_WEIGHT * sdf["dur_norm"] + OVERLAP_WEIGHT * sdf["overlap_norm"]
    sdf["cascade_prob"] = (PROB_FLOOR + (PROB_CEIL - PROB_FLOOR) * sdf["susceptibility"]).round(3)
    sdf = sdf.sort_values("cascade_prob", ascending=False)

    print(f"\nLearned cascade weights for {len(sdf)} corridors "
          f"(>= {MIN_INCIDENTS} incidents):\n")
    print(f"  {'corridor':<26}{'n':>5}{'mean_dur':>10}{'overlap':>9}{'cascade':>9}")
    for _, r in sdf.iterrows():
        print(f"  {r['corridor'][:25]:<26}{int(r['n']):>5}{r['mean_dur']:>10.0f}"
              f"{r['overlap']:>9.2f}{r['cascade_prob']:>9.3f}")

    weights = {r["corridor"]: float(r["cascade_prob"]) for _, r in sdf.iterrows()}
    default = float(round(sdf["cascade_prob"].median(), 3))

    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    body = ",\n".join(f"  {json.dumps(k)}: {v}" for k, v in weights.items())
    ts = (
        "// AUTO-GENERATED by apps/ml/scripts/compute_edge_weights.py — do not edit by hand.\n"
        "// Per-corridor cascade (spillover) probability learned from Astram incident history:\n"
        "// blend of normalised mean clearance time and intra-corridor temporal overlap rate.\n"
        f"// Corridors with < {MIN_INCIDENTS} incidents are absent and use DEFAULT_CASCADE.\n\n"
        "export const CORRIDOR_CASCADE: Record<string, number> = {\n"
        f"{body},\n"
        "}\n\n"
        f"export const DEFAULT_CASCADE = {default}\n"
    )
    OUT_TS.write_text(ts)
    print(f"\n  default (median) = {default}")
    print(f"  wrote {OUT_TS}\n")


if __name__ == "__main__":
    main()
