// AUTO-GENERATED by apps/ml/scripts/compute_edge_weights.py — do not edit by hand.
// Per-corridor cascade (spillover) probability learned from Astram incident history:
// blend of normalised mean clearance time and intra-corridor temporal overlap rate.
// Corridors with < 15 incidents are absent and use DEFAULT_CASCADE.

export const CORRIDOR_CASCADE: Record<string, number> = {
  'ORR North 1': 0.804,
  'ORR West 1': 0.774,
  'ORR East 1': 0.769,
  'Bellary Road 1': 0.736,
  'Airport New South Road': 0.72,
  'Tumkur Road': 0.706,
  'Bellary Road 2': 0.7,
  'CBD 2': 0.689,
  'Mysore Road': 0.666,
  'ORR East 2': 0.645,
  'Magadi Road': 0.636,
  'Hosur Road': 0.634,
  'Old Madras Road': 0.623,
  'Hennur Main Road': 0.58,
  'Old Airport Road': 0.578,
  'Bannerghata Road': 0.505,
  'West of Chord Road': 0.498,
  'ORR North 2': 0.492,
  'Varthur Road': 0.466,
}

export const DEFAULT_CASCADE = 0.645
